---
abstract: 'read multiple hunks of data out of your DATA section'
author:
  - 'Ricardo SIGNES <rjbs@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100730'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Section
requires:
  MRO::Compat: 0.09
  Sub::Exporter: 0.979
  Test::More: 0.88
resources:
  repository: git://git.codesimply.com/Data-Section.git
version: 0.100770
